#!/bin/bash
#
# i3-rename-workspace: rename the focused workspace
#
# usage: write in ~/.config/i3/config
#	 bindsym $mod+n exec path/to/i3-rename-workspace


# find the focused workspace

WS=$(i3-msg -t 'get_workspaces'            \
	    | sed -e 's/"num"/\n"num"/g'   \
	    | grep \"focused\":true        \
	    | sed -e 's/,"/\n/g'           \
	    | grep name                    \
	    | cut -d\" -f 3)


# find the name of workspace

WS_TEXT=$(echo $WS | cut -d' ' -f 2)


# find the number of workspace

WS_NR=$(echo $WS   | cut -d' ' -f 1)


# use zenity to input a new name

NEW=$(zenity --text="Enter new name:"       \
	     --entry                        \
	     --title="Rename workspace $WS" \
	     --entry-text="$WS_TEXT")


# rename

i3-msg "rename workspace \"$WS\" to \"$WS_NR [$NEW]\"" 
